# import = ["/Users/yangukheo/.config/alacritty/themes/themes/gruvbox_dark.toml"]
import = ["/Users/yangukheo/.config/alacritty/themes/themes/gruvbox_material_hard_dark.toml"]
live_config_reload = true
working_directory = "./Desktop"

[shell]
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[colors]
transparent_background_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12.0
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[keyboard]
bindings = [
  { key = "F", mods = "Command|Control", action = "ToggleSimpleFullscreen" },
]

[mouse]
hide_when_typing = true

[window]
decorations = "Buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"
title = "Alacritty"
padding = { x = 5, y = 5 }
dimensions = { columns = 120, lines = 40 }
opacity = 0.90
