import = ["/Users/yangukheo/.config/alacritty/themes/themes/kanagawa_wave.toml"]
live_config_reload = true
working_directory = "./Desktop"

[colors]
transparent_background_colors = true

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F"
mods = "Command|Control"

[mouse]
hide_when_typing = true

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[window]
decorations = "buttonless"
dynamic_padding = true
option_as_alt = "OnlyLeft"
title = "Alacritty"

[window.dimensions]
columns = 120
lines = 40

[window.padding]
x = 5
y = 5
