# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.42.2"
"rocks-treesitter.nvim" = "1.2.0"
"rocks-lazy.nvim" = "1.1.1"
"rocks-git.nvim" = "2.5.1"
"rocks-config.nvim" = "3.1.0"
"oil.nvim" = "2.13.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
"nvim-lspconfig" = "1.0.0"
"friendly-snippets" = "scm"
"conform.nvim" = "8.2.0"
nvim-web-devicons = "0.100"
"trouble.nvim" = "3.6.0"
"telescope.nvim" = "scm"
"nvim-notify" = "3.14.0"
nvim-surround = "2.1.5"
"nvim-ts-autotag" = "scm"
"nvim-ts-context-commentstring" = "scm"
"dressing.nvim" = "3.1.0"
nvim-ufo = "1.4.0"
"statuscol.nvim" = "scm"
"aerial.nvim" = "2.3.1"
"gitsigns.nvim" = "0.9.0"
luasnip = "2.3.0"
"typescript-tools.nvim" = "scm"
rustaceanvim = "5.18.0"
"leap.nvim" = "scm"
nvim-spectre = "scm"
"diffview.nvim" = "scm"
tree-sitter-tsx = "0.0.31"
tree-sitter-zig = "0.0.32"
tree-sitter-toml = "0.0.31"
tree-sitter-lua = "0.0.31"
tree-sitter-json = "0.0.33"
"lualine.nvim" = "scm"
"plenary.nvim" = "scm"
tree-sitter-http = "0.0.32"
tree-sitter-markdown = "0.0.36"
tree-sitter-gitignore = "0.0.29"
tree-sitter-bash = "0.0.36"
tree-sitter-git_config = "0.0.29"
tree-sitter-xml = "0.0.34"
tree-sitter-tmux = "0.0.29"
"toggleterm.nvim" = "2.13.0"

[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"
rev = "c810500b69cb8bcea58f2be635cb1340011714b5"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v0.7.3"
build = "cargo build --release"

[plugins."gx.nvim"]
git = "chrishrb/gx.nvim"
rev = "v0.7.0"
keys = [{ lhs = "gx", mode = "n" }, { lhs = "gx", mode = "x" }]

[plugins."debugprint.nvim"]
git = "andrewferrier/debugprint.nvim"
rev = "v3.7.0"
keys = [{ lhs = "g?", mode = "n" }, { lhs = "g?", mode = "x" }]

[plugins."kulala.nvim"]
git = "mistweaverco/kulala.nvim"
ft = "http"
rev = "v4.4.1"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.9.1"

[plugins.blink-cmp-copilot]
git = "giuxtaposition/blink-cmp-copilot"
rev = "e3eedf36ceda1932e296ec894de4ceea8ddeacb6"

[plugins.nvim]
git = "catppuccin/nvim"
rev = "v1.9.0"

[treesitter]
auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_install = "prompt"

[config]
plugins_dir = "plugins/"
auto_setup = false

[bundles.lsp] # Create a bundle called `lsp`
items = [
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-lspconfig",
  "friendly-snippets",
  "luasnip",
]

[bundles.cmp]
items = ["luasnip", "blink.cmp"]
