# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.43.0"
"rocks-treesitter.nvim" = "1.3.0"
"rocks-lazy.nvim" = "1.1.1"
"rocks-git.nvim" = "2.5.2"
"rocks-config.nvim" = "3.1.0"
"oil.nvim" = "2.14.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
"nvim-lspconfig" = "1.3.0"
nvim-web-devicons = "0.100"
"nvim-notify" = "3.15.0"
nvim-surround = "2.1.5"
"nvim-ts-autotag" = "scm"
"nvim-ts-context-commentstring" = "scm"
"dressing.nvim" = "3.1.1"
nvim-ufo = "1.4.0"
"statuscol.nvim" = "scm"
"gitsigns.nvim" = "0.9.0"
"typescript-tools.nvim" = "scm"
rustaceanvim = "5.22.0"
"leap.nvim" = "scm"
"trouble.nvim" = "3.6.0"
"lualine.nvim" = "scm"
tree-sitter-tsx = "0.0.32"
tree-sitter-zig = "0.0.34"
tree-sitter-toml = "0.0.31"
tree-sitter-lua = "0.0.32"
tree-sitter-json = "0.0.33"
tree-sitter-http = "0.0.33"
tree-sitter-markdown = "0.0.37"
tree-sitter-gitignore = "0.0.29"
tree-sitter-bash = "0.0.37"
tree-sitter-git_config = "0.0.29"
tree-sitter-xml = "0.0.35"
tree-sitter-tmux = "0.0.29"
tree-sitter-prisma = "0.0.29"
tree-sitter-javascript = "0.0.33"
tree-sitter-gitcommit = "0.0.33"
tree-sitter-yaml = "0.0.30"
tree-sitter-html = "0.0.33"
tree-sitter-markdown_inline = "0.0.37"
tree-sitter-rust = "0.0.38"
nvim-highlight-colors = "scm"
tree-sitter-jsonc = "0.0.29"
"which-key.nvim" = "3.15.0"
"conform.nvim" = "8.3.0"
"zen-mode.nvim" = "1.4.0"
"telescope.nvim" = "scm"
"toggleterm.nvim" = "2.13.1"
"nvim-spectre" = "scm"
"diffview.nvim" = "scm"
"aerial.nvim" = "2.4.0"
"nvim-autopairs" = "scm"
luasnip = "2.3.0"
"lazygit.nvim" = "scm"
tree-sitter-css = "0.0.31"
tree-sitter-ini = "0.0.29"
tree-sitter-editorconfig = "0.0.46"

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
rev = "v0.10.0"

[plugins."gx.nvim"]
git = "chrishrb/gx.nvim"
keys = [{ lhs = "gx", mode = "n" }, { lhs = "gx", mode = "x" }]
rev = "v0.7.0"

[plugins."debugprint.nvim"]
git = "andrewferrier/debugprint.nvim"
keys = [{ lhs = "g?", mode = "n" }, { lhs = "g?", mode = "x" }]
rev = "v4.0.0"

[plugins."kulala.nvim"]
git = "mistweaverco/kulala.nvim"
ft = "http"
rev = "v4.4.1"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"
rev = "v1.9.1"

[plugins.blink-cmp-copilot]
git = "giuxtaposition/blink-cmp-copilot"
rev = "c5c5cbce5748d21073f1d5348a92ebe6ce63f387"

[plugins.nvim]
git = "catppuccin/nvim"
rev = "v1.9.0"

[plugins."mason-conform.nvim"]
git = "zapling/mason-conform.nvim"
rev = "abce2be529f3b4b336c56d0ba6336a9144e0fee6"

[plugins.harpoon]
git = "ThePrimeagen/harpoon"
branch = "harpoon2"
keys = [
  { lhs = "<leader>ha", mode = "n", desc = "[h]arpoon [a]dd" },
  { lhs = "<C-e>", mode = "n", desc = "[h]arpoon m[e]nu" },
  # { lhs = "<A-N>", mode = "n", desc = "harpoon next" },
  # { lhs = "<A-P>", mode = "n" desc = "harpoon prev " }},
  { lhs = "<A-1>", mode = "n", desc = "harpoon select 1" },
  { lhs = "<A-2>", mode = "n", desc = "harpoon select 2" },
  { lhs = "<A-3>", mode = "n", desc = "harpoon select 3" },
  { lhs = "<A-4>", mode = "n", desc = "harpoon select 4" },
]

[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"
rev = "886ee73b6d464b2b3e3e6a7ff55ce87feac423a9"

[plugins.friendly-snippets]
git = "rafamadriz/friendly-snippets"
rev = "efff286dd74c22f731cdec26a70b46e5b203c619"

[treesitter]
auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_install = "prompt"

[config]
plugins_dir = "plugins/"
auto_setup = false

[bundles.lsp] # Create a bundle called `lsp`
items = [
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-lspconfig",
  "typescript-tools.nvim",
  "luasnip",
  "rustaceanvim",
  "blink.cmp",
]

[bundles.cmp]
items = ["luasnip", "blink.cmp", "friendly-snippets", "blink-cmp-copilot"]

[bundles."conform-mason"]
items = ["mason.nvim", "conform.nvim", "mason-conform.nvim"]
