# This is your rocks.nvim plugins declaration file.
# Here is a small yet pretty detailed example on how to use it:
#
# [plugins]
# nvim-treesitter = "semver_version"  # e.g. "1.0.0"

# List of non-Neovim rocks.
# This includes things like `toml` or other lua packages.
[rocks]

# List of Neovim plugins to install alongside their versions.
# If the plugin name contains a dot then you must add quotes to the key name!
[plugins]
"rocks.nvim" = "2.42.2"
"rocks-treesitter.nvim" = "1.2.0"
"rocks-lazy.nvim" = "1.1.1"
"rocks-git.nvim" = "2.5.2"
"rocks-config.nvim" = "3.1.0"
"oil.nvim" = "2.13.0"
"mason.nvim" = "1.10.0"
"mason-lspconfig.nvim" = "1.31.0"
"nvim-lspconfig" = "1.0.0"
nvim-web-devicons = "0.100"
"nvim-notify" = "3.14.0"
nvim-surround = "2.1.5"
"nvim-ts-autotag" = "scm"
"nvim-ts-context-commentstring" = "scm"
"dressing.nvim" = "3.1.0"
nvim-ufo = "1.4.0"
"statuscol.nvim" = "scm"
"gitsigns.nvim" = "0.9.0"
"typescript-tools.nvim" = "scm"
rustaceanvim = "5.18.0"
"leap.nvim" = "scm"
"trouble.nvim" = "3.6.0"
"lualine.nvim" = "scm"
tree-sitter-tsx = "0.0.31"
tree-sitter-zig = "0.0.32"
tree-sitter-toml = "0.0.31"
tree-sitter-lua = "0.0.31"
tree-sitter-json = "0.0.33"
tree-sitter-http = "0.0.32"
tree-sitter-markdown = "0.0.37"
tree-sitter-gitignore = "0.0.29"
tree-sitter-bash = "0.0.36"
tree-sitter-git_config = "0.0.29"
tree-sitter-xml = "0.0.34"
tree-sitter-tmux = "0.0.29"
tree-sitter-prisma = "0.0.29"
tree-sitter-javascript = "0.0.33"
tree-sitter-gitcommit = "0.0.33"
tree-sitter-yaml = "0.0.30"
tree-sitter-html = "0.0.33"
tree-sitter-markdown_inline = "0.0.37"
tree-sitter-rust = "0.0.37"
nvim-highlight-colors = "scm"
tree-sitter-jsonc = "0.0.29"
"which-key.nvim" = "3.14.1"
"conform.nvim" = "8.2.0"

[plugins."friendly-snippets"]
git = "rafamadriz/friendly-snippets"

[plugins."copilot.lua"]
git = "zbirenbaum/copilot.lua"

[plugins.harpoon]
git = "ThePrimeagen/harpoon"
branch = "harpoon2"
keys = [
  { lhs = "<leader>ha", mode = "n" },
  { lhs = "<C-e>", mode = "n" },
  { lhs = "<A-1>", mode = "n" },
  { lhs = "<A-2>", mode = "n" },
  { lhs = "<A-3>", mode = "n" },
  { lhs = "<A-4>", mode = "n" },
]

[plugins."nvim-autopairs"]
version = "scm"
event = "InsertEnter"

[plugins."aerial.nvim"]
version = "2.3.1"
cmd = "AerialToggle"
keys = [{ lhs = "<leader>a", mode = "n" }]

[plugins."telescope.nvim"]
version = "scm"
cmd = "Telescope"
keys = [
  { lhs = "<leader>fw", mode = "n" },
  { lhs = "<leader>fb", mode = "n" },
  { lhs = "<leader>fh", mode = "n" },
  { lhs = "<leader>ma", mode = "n" },
  { lhs = "<leader>fo", mode = "n" },
  { lhs = "<leader>fz", mode = "n" },
  { lhs = "<leader>cm", mode = "n" },
  { lhs = "<leader>gt", mode = "n" },
  { lhs = "<leader>ff", mode = "n" },
  { lhs = "<leader>fa", mode = "n" },
]

[plugins."diffview.nvim"]
version = "scm"
cmd = "DiffviewOpen"
keys = [
  { lhs = "<leader>do", mode = "n" },
  { lhs = "<leader>dv", mode = "n" },
  { lhs = "<leader>dc", mode = "n" },
]

[plugins."toggleterm.nvim"]
version = "2.13.0"
keys = [
  { lhs = "<A-v>", mode = "n" },
  { lhs = "<A-v>", mode = "t" },
  { lhs = "<A-h>", mode = "n" },
  { lhs = "<A-h>", mode = "t" },
  { lhs = "<A-i>", mode = "n" },
  { lhs = "<A-i>", mode = "t" },
  { lhs = "<leader>lg", mode = "n" },
]

[plugins."nvim-spectre"]
version = "scm"
keys = [
  { lhs = "<leader>sw", mode = "n" },
  { lhs = "<leader>sw", mode = "v" },
  { lhs = "<leader>S", mode = "n" },
  { lhs = "<leader>sp", mode = "n" },
]

[plugins."blink.cmp"]
git = "saghen/blink.cmp"
build = "cargo build --release"

[plugins."gx.nvim"]
git = "chrishrb/gx.nvim"
keys = [{ lhs = "gx", mode = "n" }, { lhs = "gx", mode = "x" }]

[plugins."debugprint.nvim"]
git = "andrewferrier/debugprint.nvim"
keys = [{ lhs = "g?", mode = "n" }, { lhs = "g?", mode = "x" }]

[plugins."kulala.nvim"]
git = "mistweaverco/kulala.nvim"
ft = "http"

[plugins."barbar.nvim"]
git = "romgrk/barbar.nvim"

[plugins.blink-cmp-copilot]
git = "giuxtaposition/blink-cmp-copilot"

[plugins.luasnip]
git = "L3MON4D3/LuaSnip"

[plugins.nvim]
git = "catppuccin/nvim"

[plugins."mason-conform.nvim"]
git = "zapling/mason-conform.nvim"

[treesitter]
auto_highlight = "all"
# NOTE: These are parsers, not filetypes.
auto_install = "prompt"

[config]
plugins_dir = "plugins/"
auto_setup = false

[bundles.lsp] # Create a bundle called `lsp`
items = [
  "mason.nvim",
  "mason-lspconfig.nvim",
  "nvim-lspconfig",
  "typescript-tools.nvim",
  "luasnip",
  "rustaceanvim",
  "blink.cmp",
]

[bundles.cmp]
items = ["luasnip", "blink.cmp", "friendly-snippets"]

[bundles."conform-mason"]
items = [
  "mason.nvim",
  "conform.nvim",
  "mason-conform.nvim",
  "blink-cmp-copilot",
]
